version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "8084:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dummydb
    ports:
      - "3306:3306"
      
version: '3.8'
services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar-db:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:lts
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs

volumes:
  sonar-db:
  sonarqube-data:
  sonarqube-logs:

  version: '3.8'
services:
  nexus:
    image: sonatype/nexus3:latest
    restart: unless-stopped
    ports:
      - "8081:8081"   # Nexus UI
      - "8082:8082"   # Docker Registry
    volumes:
      - nexus-data:/nexus-data

volumes:
  nexus-data:


